apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: function-put
        image: myfunctionput:latest
        env:
        - name: AzureWebJobsStorage
          valueFrom:
            secretKeyRef:
              name: mysecrets
              key: AzureWebJobsStorage
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
      - name: function-load
        image: myfunctionload:latest
        env:
        - name: AzureWebJobsStorage
          valueFrom:
            secretKeyRef:
              name: mysecrets
              key: AzureWebJobsStorage
        - name: AzureFunctionsJobHost__functions__0
          value: QueueTrigger
        - name: AzureFunctionsJobHost__functions__0__type
          value: queueTrigger
        - name: AzureFunctionsJobHost__functions__0__direction
          value: in
        - name: AzureFunctionsJobHost__functions__0__queueName
          value: myqueue
        - name: AzureFunctionsJobHost__functions__0__connection
          value: AzureWebJobsStorage
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
      - name: container-service
        image: mycontainerservice:latest
        env:
        - name: MESSAGE
          value: "Hello World"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
 
