apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-function
  labels:
    app: azure-function
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-function
  template:
    metadata:
      labels:
        app: azure-function
    spec:
      containers:
      - name: azure-function
        image: <your-container-registry>/<your-image-name>:<your-image-tag>
        env:
        - name: AzureWebJobsStorage
          value: <your-storage-account-connection-string>
        resources:
          limits:
            cpu: 0.5
            memory: "256Mi"
          requests:
            cpu: 0.5
            memory: "256Mi"
