apiVersion networking.k8s.iov1
kind Ingress
metadata
  name myapp
spec
  rules
  - host myapp.example.com
    http
      paths
      - path 
        pathType Prefix
        backend
          service
            name myapp
            port
              name http